name: Auto Update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  autoupdate:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Scoop
        run: |
          Set-ExecutionPolicy RemoteSigned -Scope CurrentUser -Force
          irm get.scoop.sh | iex

      - name: Run autoupdate
        run: |
          . "$env:USERPROFILE\scoop\apps\scoop\current\bin\scoop.ps1"
          scoop bucket add rakujitsu $env:GITHUB_WORKSPACE
          scoop update
          pwsh "$env:SCOOP\apps\scoop\current\bin\auto-update.ps1" -Dir "$env:GITHUB_WORKSPACE" -Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
